[project]
name = "vfio-auto"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "kunihir0", email = kunihiro@tutanota.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
